name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - master
      - develop

env:
  JAVA_VERSION: "${{ secrets.SMS_JAVA_VERSION }}"

defaults: 
  run:
    shell: bash

jobs:
  test:
    if: github.ref == 'refs/heads/feature/*' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/gradle-test.yml@main

  # build:
  #   if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: build 
  #     uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/gradle-build.yml@main
  #     with:
  #       job: build

  other:
    env:
      APPLICATION_NAME: sms-infrastructure
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/other-create-application-yml.yml@main
    with:
      application_name: ${{ env.APPLICATION_NAME }}


  package:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/docker-packaging.yml@main


  deploy:
    if: github.ref == 'refs/heads/master'
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/deploy-ssh-to-ec2.yml@main
