name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - master
      - develop

env:
  JAVA_VERSION: "${{ secrets.SMS_JAVA_VERSION }}"

defaults: 
  run:
    shell: bash


jobs:
  test:
    if: github.ref == 'refs/heads/feature/*' || github.ref == 'refs/heads/develop', || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: test
      uses: ./.github/workflows/gradle-test.yml
      with:
        job: test


          
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    - uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/gradle-build.yml@main
      with:
        job: build

  other:
    runs-on: ubuntu-latest
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/other-create-application-yml.yml@main
    with:
      application_name: sms-infrastructure
      job: check-and-create-application-yml
        

  package:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/docker-packaging.yml@main
    with:
      job: package

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/deploy-ssh-to-ec2.yml@main
    with:
      job: deploy
    