name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - master
      - develop

defaults: 
  run:
    shell: bash

jobs:
  test:
    if: github.ref == 'refs/heads/feature/*' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/gradle-test.yml@main

  build:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/gradle-build.yml@main

  other:
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/other-create-application-yml.yml@main
    with:
      application_name: sms-infrastructure


  package:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/docker-packaging.yml@main


  production-deploy:
    if: github.ref == 'refs/heads/master'
    uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/deploy-ssh-to-ec2.yml@main

  # develop-deploy:
  #   if: github.ref == 'ref/heads/develop'
  #   uses: GSM-MSG/sugar-cane-pipeline/.github/workflows/deploy-ssh-to-ec2.yml@main
